name: disc-with-replogle
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults

dependencies:
  # Core scientific computing
  - python>=3.9
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0

  # Machine learning and deep learning
  - pytorch>=2.0.0
  - scikit-learn>=1.3.0

  # Single-cell analysis
  - scanpy>=1.9.0
  - anndata>=0.9.0

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0

  # Graph analysis
  - networkx>=3.0
  - torch-geometric

  # Configuration and utilities
  - pyyaml>=6.0
  - requests>=2.31.0
  - jinja2>=3.1.0

  # Development and testing
  - pytest>=7.4.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0

  # Data format support
  - h5py>=3.9.0
  - pytables>=3.8.0

  # Additional dependencies via pip
  - pip
  - pip:
    - goatools>=1.3.0  # Not available in conda-forge, install via pip
