name: disc-with-replogle
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core
  - python=3.12
  - pip
  - jupyter
  - ipykernel

  # Scientific Computing
  - numpy
  - pandas
  - scipy
  - scikit-learn

  # PyTorch & Geometric
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg

  # Single-Cell & Bio
  - scanpy
  - anndata
  - networkx
  - h5py
  - pytables

  # Visualization
  - matplotlib
  - seaborn
  - plotly

  # Utilities
  - pyyaml
  - requests
  - jinja2
  - tqdm

  # Development
  - pytest
  - tensorboard

  # Pip-only packages
  - pip:
    - goatools>=1.3.0