# Configuration for cell-specific graph generation (03b_generate_cell_graphs.py)

# Key to identify control perturbations in the 'condition' column of AnnData.
# This is used to set the 'is_control' flag in the PyG Data objects.
control_key: "ctrl"

# Future parameters could be added here, for example:
# - Options for different ways to construct the edge_index
# - Subsampling strategies for large datasets
# - Additional metadata to include in the graph objects
