# Data processing configuration for Replogle 2022 K562 Perturb-seq dataset

qc_thresholds:
  # Cell-level QC filters
  min_genes_per_cell: 50      # Reduced from 200 - more permissive for this dataset
  max_genes_per_cell: 10000   # Increased from 8000
  min_total_counts_per_cell: 100    # Reduced from 1000 significantly
  max_total_counts_per_cell: 100000 # Increased from 50000
  max_mitochondrial_fraction: 0.3   # Increased from 0.2
  
  # Gene-level QC filters  
  min_cells_per_gene: 3

guide_filtering:
  # Guide assignment and filtering parameters
  max_guides_per_cell: 3
  min_cells_per_guide: 5      # Reduced from 10 for better retention
  control_guide_names:
    - "non-targeting"
    - "scrambled"
    - "control"
    - "NT"

gene_filtering:
  # Additional gene filtering options
  filter_mitochondrial: true
  filter_ribosomal: true
  min_expression_level: 0.01

normalization:
  # Normalization and transformation parameters
  target_sum: 10000
  log_transform: true
  hvg_selection: true
  hvg_method: "seurat_v3"
  hvg_n_top_genes: 2000

data_splitting:
  # Data splitting configuration
  train_fraction: 0.7
  val_fraction: 0.15
  test_fraction: 0.15
  random_seed: 42
  stratify_by: "guide_identity"
